version: "3.9"
services:

  nginx:
    build: ./
    volumes:
      - ./:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - node-network

  node:
    container_name: "node_server"
    build: ./frontend
    expose:
      - "8080"
    networks:
      - node-network

networks:
  node-network:
    name: node-network
    driver: bridge  