// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Вернуть объявления из корзины.
	// (GET /api/cart)
	GetCart(ctx echo.Context) error
	// Удалить из корзины товар.
	// (DELETE /api/cart/{id})
	RemoveCart(ctx echo.Context, id string) error
	// Добавить в корзину.
	// (POST /api/cart/{id})
	AddCart(ctx echo.Context, id string) error
	// Закрыть объявление.
	// (PUT /api/close/{userId}/{id})
	ClosePost(ctx echo.Context, userId string, id string) error
	// Вернуть избранное.
	// (GET /api/favorite)
	GetFavorite(ctx echo.Context) error
	// Удалить из избранных товар.
	// (DELETE /api/favorite/{id})
	RemoveFavorite(ctx echo.Context, id string) error
	// Добавить в избранное.
	// (POST /api/favorite/{id})
	AddFavorite(ctx echo.Context, id string) error
	// Создать новое объявление.
	// (POST /api/post)
	CreatePost(ctx echo.Context) error
	// Вернуть закрытые объявления по id пользователя.
	// (GET /api/post/close/user/{idUser}/{page})
	FindClosePostByUserID(ctx echo.Context, idUser string, page int) error
	// Вернуть открытые объявления по id пользователя.
	// (GET /api/post/open/user/{idUser}/{page})
	FindOpenPostByUserID(ctx echo.Context, idUser string, page int) error
	// Удалить объявление.
	// (DELETE /api/post/{id})
	DeletePost(ctx echo.Context, id string) error
	// Вернуть объявление по id.
	// (GET /api/post/{id})
	FindPostByID(ctx echo.Context, id string) error
	// Обновить объявление.
	// (PUT /api/post/{id})
	UpdatePost(ctx echo.Context, id string) error
	// Вернуть объявления по тегу.
	// (GET /api/post/{tag}/{page})
	FindPostByTag(ctx echo.Context, tag string, page int) error
	// Основнвая страница
	// (GET /api/sort/new/{page})
	GetAllPost(ctx echo.Context, page int) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetCart converts echo context to params.
func (w *ServerInterfaceWrapper) GetCart(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetCart(ctx)
	return err
}

// RemoveCart converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveCart(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RemoveCart(ctx, id)
	return err
}

// AddCart converts echo context to params.
func (w *ServerInterfaceWrapper) AddCart(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AddCart(ctx, id)
	return err
}

// ClosePost converts echo context to params.
func (w *ServerInterfaceWrapper) ClosePost(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithLocation("simple", false, "userId", runtime.ParamLocationPath, ctx.Param("userId"), &userId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ClosePost(ctx, userId, id)
	return err
}

// GetFavorite converts echo context to params.
func (w *ServerInterfaceWrapper) GetFavorite(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFavorite(ctx)
	return err
}

// RemoveFavorite converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveFavorite(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RemoveFavorite(ctx, id)
	return err
}

// AddFavorite converts echo context to params.
func (w *ServerInterfaceWrapper) AddFavorite(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AddFavorite(ctx, id)
	return err
}

// CreatePost converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePost(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreatePost(ctx)
	return err
}

// FindClosePostByUserID converts echo context to params.
func (w *ServerInterfaceWrapper) FindClosePostByUserID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "idUser" -------------
	var idUser string

	err = runtime.BindStyledParameterWithLocation("simple", false, "idUser", runtime.ParamLocationPath, ctx.Param("idUser"), &idUser)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter idUser: %s", err))
	}

	// ------------- Path parameter "page" -------------
	var page int

	err = runtime.BindStyledParameterWithLocation("simple", false, "page", runtime.ParamLocationPath, ctx.Param("page"), &page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindClosePostByUserID(ctx, idUser, page)
	return err
}

// FindOpenPostByUserID converts echo context to params.
func (w *ServerInterfaceWrapper) FindOpenPostByUserID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "idUser" -------------
	var idUser string

	err = runtime.BindStyledParameterWithLocation("simple", false, "idUser", runtime.ParamLocationPath, ctx.Param("idUser"), &idUser)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter idUser: %s", err))
	}

	// ------------- Path parameter "page" -------------
	var page int

	err = runtime.BindStyledParameterWithLocation("simple", false, "page", runtime.ParamLocationPath, ctx.Param("page"), &page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindOpenPostByUserID(ctx, idUser, page)
	return err
}

// DeletePost converts echo context to params.
func (w *ServerInterfaceWrapper) DeletePost(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeletePost(ctx, id)
	return err
}

// FindPostByID converts echo context to params.
func (w *ServerInterfaceWrapper) FindPostByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindPostByID(ctx, id)
	return err
}

// UpdatePost converts echo context to params.
func (w *ServerInterfaceWrapper) UpdatePost(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdatePost(ctx, id)
	return err
}

// FindPostByTag converts echo context to params.
func (w *ServerInterfaceWrapper) FindPostByTag(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "tag" -------------
	var tag string

	err = runtime.BindStyledParameterWithLocation("simple", false, "tag", runtime.ParamLocationPath, ctx.Param("tag"), &tag)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag: %s", err))
	}

	// ------------- Path parameter "page" -------------
	var page int

	err = runtime.BindStyledParameterWithLocation("simple", false, "page", runtime.ParamLocationPath, ctx.Param("page"), &page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindPostByTag(ctx, tag, page)
	return err
}

// GetAllPost converts echo context to params.
func (w *ServerInterfaceWrapper) GetAllPost(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "page" -------------
	var page int

	err = runtime.BindStyledParameterWithLocation("simple", false, "page", runtime.ParamLocationPath, ctx.Param("page"), &page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetAllPost(ctx, page)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/cart", wrapper.GetCart)
	router.DELETE(baseURL+"/api/cart/:id", wrapper.RemoveCart)
	router.POST(baseURL+"/api/cart/:id", wrapper.AddCart)
	router.PUT(baseURL+"/api/close/:userId/:id", wrapper.ClosePost)
	router.GET(baseURL+"/api/favorite", wrapper.GetFavorite)
	router.DELETE(baseURL+"/api/favorite/:id", wrapper.RemoveFavorite)
	router.POST(baseURL+"/api/favorite/:id", wrapper.AddFavorite)
	router.POST(baseURL+"/api/post", wrapper.CreatePost)
	router.GET(baseURL+"/api/post/close/user/:idUser/:page", wrapper.FindClosePostByUserID)
	router.GET(baseURL+"/api/post/open/user/:idUser/:page", wrapper.FindOpenPostByUserID)
	router.DELETE(baseURL+"/api/post/:id", wrapper.DeletePost)
	router.GET(baseURL+"/api/post/:id", wrapper.FindPostByID)
	router.PUT(baseURL+"/api/post/:id", wrapper.UpdatePost)
	router.GET(baseURL+"/api/post/:tag/:page", wrapper.FindPostByTag)
	router.GET(baseURL+"/api/sort/new/:page", wrapper.GetAllPost)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaT2/bNhT/KgK3oxC7zU6+pc3aZcDQYEu2Q5cDazE2B1lSSTpFYAiwHawrlgJBhwEb",
	"BrRFN2Bn140bN2nUr/D4jQaS8h/FVOwi6ZqkPiWmJPK99/u9936k1EDlsBaFAQkER6UG4uUqqWH9701G",
	"sCCrIRfqF/b9O5uodLeBIhZGhAlK9F3LhJcZjQQNA/XTG/+J4AUksA892YTX0IFj6EPPgQReyl/lHnTh",
	"CHpqUO4tIBeJ7YigEuKC0aCCYhetYlFdqeGKWYgKUuOWJf6EAz1jEzrw2swHPet86QBmDG/r+RktE8uM",
	"/+pZOrMbuoYrlmn+go5sQw9eQSKb+c9S4duMeAodOICuiZrcm9WY2EWM3K9TRjxUupvO7mZQGjhu7M6E",
	"eSPeiF30JWMh+2ptbVWZlUW7HHoWY/UDjr7mos2Q1bBAJUQDsXh9ZCENBKkQpnyuEc5xJXeiweVpzqUL",
	"Dm5Xpn9DAzqNsR+cViEXK97klCvL70H9c6Pm+dLLReucsDzv3kECR/Kxjlw3Zf9RzjzfU/KAW7MmgSPo",
	"y1+gJ1uyDV1IHHgnm5DIFryFRLbV/9BdsDDrBD9SU91hFqTIDBYfJcJECkzj0E0/5Law/gEdOJRNuSvb",
	"yu4j6Fsim+HRvTD0CQ5USOal9EKV0lO47l18rp9W8Q17x9IgS//YRZyU64yK7e+UHDCkuUcwI2ypLqqj",
	"X7cGtf7rH9aQa8SDJrW+OrK6KkSEYjUxDTbDyUjciUiwFFFncaHowL6KoyNbmutd6MsWdJwo5EKNdeCN",
	"bEPHWYqi9YDe15ExsKN0yPmxXiwuljlhW7RMHJXJeoQ4S6sryEVbhHGz6rWF4kJR4RNGJMARRSW0qIdc",
	"FGFR1V4XcEQLZcx0NagQ/UcVAqwsV9xAt4m4qa4rPHgUBtyE63qxaBpmIEhgakkU+bSsHyz8xE2OG7ll",
	"oUZX+Z/L1GEChwGx1id65gp9gl/USytjNvPVbScsfzZp8mDdHcV0OIZkAennNnHdF+8Vpc8Z2UQl9Flh",
	"pFoLqWQtjGSLzaznOpX6ynP5CI50TZKPoA8v4RA6C2ic9Tqg43y/uxFvuIjXazXMttVsv2lyHssd2ZaP",
	"rTA5ai0HDnXFOoA+HMtds8qQUoUG9WKDk08EmaTWt6QWbpGUXRFmuEYEYVybN1GRVMfRmDaVOyrTUEnz",
	"GLkowDotqYfGURWsTtyx4J5kwIad0tPwhp4jd2AfOunAVcD7n9SfvsF7Etqx8Gtno1RAZAFd8rxLiCbs",
	"K4JDZzh4FRD9fehTimk3i+jOeLKqfllo1HWPjYdpG9UtEOvequXjNJDztwNnB9vNKf720m9Zrz7QE2cm",
	"2LkwQwd0pm6jq49swTvoyUeKqTrK6p/hPZefvGPbDGv7Uap9yN5NvBUyavpLnoK5NbhnrmI+XRWjpjWb",
	"P13irSSaUbOM8WmuWy6YbsnALHflzzNrl0uK6iejX05L4AGodnDHzvoNJoSLG6G3fW6hGVsgzlZlhXs8",
	"ge21mTM20+tlCxI40KS/CiC/GHhjIDYiJrG21AmwU9WqhJwq2uucsLjQiHCFxLlK4BYNvKGAvbGtD5WW",
	"ZxGy2Y48XV4ae84maeGFbOsCo7rzw9wyE5lXCVMXGp2snVXIWnTNdG17vqrkevELSwI9kbvmSPrkGWPP",
	"tALnVMF2MXMpV80cjGnk3RyndPAcetpxbjanwogE759SdyISzDNqnlGXPKMS2T7/jJq2n1jW4x/9QGWS",
	"wTY6PLf6/Hi4r5BP4Piq7SnsSsTNr4amEs5WBf9HPD/SYdVlOVSY/d1H6pRDPbObtJ2SrkcevihZ/fE3",
	"O/Nz0g9Uqp4NPerPclJqGpLAlZlUnalj5o36qRSGv6EHr3IYK/Tzc9FWGH66NRduH7xED3Sa+agm866L",
	"h0wUAvJgWgbcJmLJ92ep4PAUEnirLHJkS8fYfIjzUEdZy0rZgkQ2ZRv65oOX4QnWGwdewr6rbxqdf7xS",
	"1epQz6aZn8Bb5cOc95r3+juDT5P3z2QrJcmx1t97JxgHHbMKJ2xrQNY689MvlHipUGhUQy4UdWKVDchF",
	"W5hRfM83VBhcNIFNA4H8sIz9atp5N+L/AgAA//9aCuz0Uy0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
