// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package v2

// CreatePost defines model for CreatePost.
type CreatePost struct {
	// Images Картинки поста.
	Images []string `json:"Images"`

	// Title Название поста.
	Title string`json:"Title"`

	// Description Описание поста.
	Desciption string	`json:"Description"`

	// Tags Описание тэгов.
	Tags []string `json:"Tags"`
}

// ErrorHTTP defines model for ErrorHTTP.
type ErrorHTTP struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// GetPost defines model for GetPost.
type GetPost struct {
	// Images Картинки поста.
	Images []string `json:"Images"`

	// Tags Тэги поста.
	Tags []string `json:"Tags"`

	// Title Название поста.
	Title string`json:"Title"`

	// Description Описание поста.
	Desciption string	`json:"Description"`

	// ID ID поста.
	ID string `json:"ID"`
}

// CreatePostJSONRequestBody defines body for CreatePost for application/json ContentType.
type CreatePostJSONRequestBody = CreatePost

// UpdatePOstJSONRequestBody defines body for UpdatePost for application/json ContentType.
type UpdatePostJSONRequestBody = CreatePost
