// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Вход в аккаунт.
	// (POST /api/auth/login)
	Login(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Login(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/api/auth/login", wrapper.Login)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xUT08bRxT/KqtpDq2y7G5wQMJSD24S6C41BmziNtiNxuuxPbDemcyMMQZZAqpWOVRC",
	"6rWHHPoFXBpUF4T7Fd58o2pm7TgEqlw4zcx7b96f3/u9d4xi1uUsJamSKH+MZNwhXWyvL4Rg4ttKZdM8",
	"uGCcCEWJVcWsSczZJDIWlCvKUpTPPjhW56IWE12sUB7RVOUWkYvUgJPsSdpEoKGLukRK3P5fRzP1h69S",
	"CZq20XDoIkHe9KggTZTfRdOAM/P60EWRZGmVNCpsn6R33UfVigNjmMAVXMINchE5xF2emBBkEHUaazEt",
	"0SjcOQqfbNBQhun2UvwsXA73+fcvn0UrHhlER81qSEs0PCzuFYONyg+50vP9fkj7tNFdVa/K1vgArz1t",
	"b6+tJEaOq6tBuMcONyovFot7xaXi83DQ2vLKrWT9sL8dlYtkfX11cavytNXnRRK1csubpf3lQfTyNW5u",
	"Sdlfij/GFHOe0Bibevy9vkIu4lgpIkx1P365ixeOCguvgoWV11/XH39Vq3mfEdVqC7Xa41rNN7pHdwF3",
	"UZm20x1uoMRJUmqh/O6nlPiOtek9WMPvMIG/YAw33n1+N7GUfSaa93x8ByN9AhO41r96n+VAFv0jf/Vh",
	"3dhIEvcEVYOyoXWWaINgQUShpzrz1+oM2KhaQW42BCZapp1H7yjF0dA4pmmL3U26xEla4NTJeYED7+Fa",
	"nzv6FC71CVzAWJ/CyOFMKiMbwT/6DEZOgfOdlL6xFVJlOTgVObVeEORiScQBjYljErYS4hQ2Q+SiAyJk",
	"FvWJF3iBQZNxkmJOUR7lrMjSomOr9jGnPu6pjp/MGmVSMafpoqVS2ET5D0gadIlU37DmIJv4VJHU2t8i",
	"n2TpfG2Y2yNBWiiPvvDne8WfLhV/yqLh7e4p0SNWIDlLZdakxSB4sKi3loGN/QnT/tCn8C9c6rdwAyN9",
	"7sAILvQZTPQJjOFvGOlfYKzPPWR/tnAvUQ+W23zH3pfYOzsAJoeJfgvXMHLsZQx/whWMPDsFstftYjEw",
	"5r/pn2EC7x24MCVcGRv9E9zoMy/zbqhEhLTD2xPJlM8y7/vHHSZVirtkaHhiyIUFxY0ka8ZMmfF9CgBK",
	"WIwTozLO68P/AgAA//8IONPXSQYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
