// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package v2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserCheck struct {
	Login                string   `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCheck) Reset()         { *m = UserCheck{} }
func (m *UserCheck) String() string { return proto.CompactTextString(m) }
func (*UserCheck) ProtoMessage()    {}
func (*UserCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCheck.Unmarshal(m, b)
}
func (m *UserCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCheck.Marshal(b, m, deterministic)
}
func (m *UserCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCheck.Merge(m, src)
}
func (m *UserCheck) XXX_Size() int {
	return xxx_messageInfo_UserCheck.Size(m)
}
func (m *UserCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCheck.DiscardUnknown(m)
}

var xxx_messageInfo_UserCheck proto.InternalMessageInfo

func (m *UserCheck) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *UserCheck) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Uuid struct {
	Value                string   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Uuid) Reset()         { *m = Uuid{} }
func (m *Uuid) String() string { return proto.CompactTextString(m) }
func (*Uuid) ProtoMessage()    {}
func (*Uuid) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *Uuid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uuid.Unmarshal(m, b)
}
func (m *Uuid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uuid.Marshal(b, m, deterministic)
}
func (m *Uuid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uuid.Merge(m, src)
}
func (m *Uuid) XXX_Size() int {
	return xxx_messageInfo_Uuid.Size(m)
}
func (m *Uuid) XXX_DiscardUnknown() {
	xxx_messageInfo_Uuid.DiscardUnknown(m)
}

var xxx_messageInfo_Uuid proto.InternalMessageInfo

func (m *Uuid) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*UserCheck)(nil), "v2.UserCheck")
	proto.RegisterType((*Uuid)(nil), "v2.Uuid")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x52, 0xb2, 0xe5, 0xe2, 0x0c, 0x2d,
	0x4e, 0x2d, 0x72, 0xce, 0x48, 0x4d, 0xce, 0x16, 0x12, 0xe1, 0x62, 0xf5, 0xc9, 0x4f, 0xcf, 0xcc,
	0x93, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0xa4, 0xb8, 0x38, 0x02, 0x12, 0x8b,
	0x8b, 0xcb, 0xf3, 0x8b, 0x52, 0x24, 0x98, 0xc0, 0x12, 0x70, 0xbe, 0x92, 0x0c, 0x17, 0x4b, 0x68,
	0x69, 0x66, 0x0a, 0x48, 0x67, 0x58, 0x62, 0x4e, 0x69, 0x2a, 0x4c, 0x27, 0x98, 0x63, 0x64, 0xc8,
	0xc5, 0x02, 0x32, 0x5c, 0x48, 0x93, 0x8b, 0x07, 0x6c, 0x81, 0x63, 0x72, 0x72, 0x7e, 0x69, 0x5e,
	0x89, 0x10, 0xaf, 0x5e, 0x99, 0x91, 0x1e, 0xdc, 0x5a, 0x29, 0x0e, 0x30, 0xb7, 0x34, 0x33, 0x45,
	0x89, 0xc1, 0x89, 0x3d, 0x8a, 0x55, 0x4f, 0xdf, 0xba, 0xcc, 0x28, 0x89, 0x0d, 0xec, 0x46, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0x83, 0x43, 0x32, 0xb1, 0x00, 0x00, 0x00,
}
