// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Удалить пользователя.
	// (DELETE /api/user)
	DeleteUser(ctx echo.Context) error
	// Вернуть данные пользователя.
	// (GET /api/user)
	GetUser(ctx echo.Context) error
	// Создать нового пользователя.
	// (POST /api/user)
	CreateUser(ctx echo.Context) error
	// Обновить пользователя.
	// (PUT /api/user)
	UpdateUser(ctx echo.Context) error
	// Вернуть пользователя по id.
	// (GET /api/user/{id})
	FindUserByID(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// DeleteUser converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteUser(ctx)
	return err
}

// GetUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUser(ctx)
	return err
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateUser(ctx)
	return err
}

// UpdateUser converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateUser(ctx)
	return err
}

// FindUserByID converts echo context to params.
func (w *ServerInterfaceWrapper) FindUserByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindUserByID(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.DELETE(baseURL+"/api/user", wrapper.DeleteUser)
	router.GET(baseURL+"/api/user", wrapper.GetUser)
	router.POST(baseURL+"/api/user", wrapper.CreateUser)
	router.PUT(baseURL+"/api/user", wrapper.UpdateUser)
	router.GET(baseURL+"/api/user/:id", wrapper.FindUserByID)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xX224aRxh+ldU0F62yBmJsS0bqBTGxu7gYH3DcxtBovDvA2OwhM4MxtpDiuFIjNVLa",
	"XlWqmqrqCxA3KNQO5BX+faNqZiGAWZ+qxnJ7t8zsfv/h+/4DB8h0bc91iCM4ShwgbpaJjdXjHCNYkHVO",
	"mPyFK5VsESU2D5DHXI8wQYl6K7mLBVZvWISbjHqCug5KIPgBjqHpP4Om/1SD99CFU/8FvIVu77gFp/7L",
	"CNKRqHsEJRAXjDol1NDRAxvTyjigOr4e0pduiTohrv0CXfgT2tC5HtwStkkI2s/wzn95PaRlzHnNZVYI",
	"2m8yYQHUP8OcKxNzJwxYwR5Dy38KJ9CU4H1L1/W+7DpkqWpvkTDef4UuvJNWtAAEWv630IVOYPKqVho6",
	"YuRJlTJiocRmTxN9Rkdd6BEzlNWzydD7Ki00ClJgjLnsi1xuWXo/qmbTtUIoVh9o6k5HRZfZWKAEoo6I",
	"Tw48p44gJcJkgmzCOS6dC9S/vizonsH+69L1BSJuviCN1K2soZtXoZE6T3oj+kpz19kgWzl3h4R0n/RG",
	"ToM2dOEEWtBBOiJ72PYq0iypp8tbCybN0rSxvm/cW6IGN5zVaXPOmDF2vK8ezqVnI6Se3rc2DJqlxl5m",
	"OxNbyn0dz6Z2agat0S17XjxaUy/v4oWp0urCbEWe4435mLHt7i3lHkxmtjPTmZRRL65E1oqVxb3aanot",
	"QxYX5ydXclPFmpch6WJ8Zjm7M1NPP3yMrRXOa9PmsPCx51WoiWU80W3uynr0sBCEyfC++XQTT+wnJx7F",
	"JmYff164+1k+H7nkKJ+fyOfv5vNReXcnlAVOzCqjor4mx1Og8y2CGWHJqigPfs33XUxv5JAeDDOJFNwO",
	"kMtCeKghgalTdMc5ynrESXpUi0diGrxRHdI/VJ3zGNr+ITS1KidMnjXhL1lSWtLz1h36RGmICsVm70jL",
	"V2OxuMkJ26Um0WT5qhOiJZcNpKNdwnhg9V4kFolJabsecbBHUQLF1ZHKb1lFHcUejVZ5X/MVIlQ5yQag",
	"CDEslEApda4ahRQw91yHB0mbjE2FzpzuWDm80PwjeANNOPV/hE5EumWRIq5WRNAnHUEc9Timhg9bhHy6",
	"w0gRJdAn0cGaEe3tGNFBH1ZUhM6rtnTLfw6nsnDlQxtey/EVGZGFaoPDgtgsNAo64lXbxqwu0f4IYoG2",
	"/+zCwdrQUYmI8ZT2G+9YPmP/WjqG9q2wfLyCk/88Cz+pGur4RwELkpIOdPzvoXUxJZ7LQzgZSljQpwkX",
	"912r/tEYGcwCwaqkMaaFexdZromrGx6ZIKG0hCZL1qx/CO+h5T+HDnRlg+rC2yDPt1U8A3X83nc2UEdH",
	"xSa3jO4l6qiGiGPds26XOG6sUVxRG9CF170c/z9a/KsP8Vza5Bv6YJBGD6jVkHGE9v156lgy0/fravnz",
	"MMM2EYRx5c9oPEbqwt1S/hVVgxzpyFFrMKIWOiscfSizZ/egwkcUVX/AXUdRvWiP/O/kKnv7G8yZ8XMO",
	"V+pCo5b8vNH4OwAA//8lJHuyIREAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
