// Package v2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package v2

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Вернуть объявления из корзины.
	// (GET /api/v1/cart)
	GetCart(ctx echo.Context) error
	// Удалить из корзины товар.
	// (DELETE /api/v1/cart/{id})
	RemoveCart(ctx echo.Context, id string) error
	// Добавить в корзину.
	// (POST /api/v1/cart/{id})
	AddCart(ctx echo.Context, id string) error
	// Вернуть избранное.
	// (GET /api/v1/favorite)
	GetFavorite(ctx echo.Context) error
	// Удалить из избранных товар.
	// (DELETE /api/v1/favorite/{id})
	RemoveFavorite(ctx echo.Context, id string) error
	// Добавить в избранное.
	// (POST /api/v1/favorite/{id})
	AddFavorite(ctx echo.Context, id string) error
	// Возврат массива постов.
	// (GET /api/v1/post)
	GetMiniPost(ctx echo.Context, params GetMiniPostParams) error
	// Создать новое объявление.
	// (POST /api/v1/post)
	CreatePost(ctx echo.Context) error
	// Удалить объявление.
	// (DELETE /api/v1/post/{id})
	DeletePost(ctx echo.Context, id string) error
	// Вернуть объявление по id.
	// (GET /api/v1/post/{id})
	FindPostByID(ctx echo.Context, id string) error
	// Обновить объявление.
	// (PUT /api/v1/post/{id})
	UpdatePost(ctx echo.Context, id string) error
	// Поиск.
	// (POST /api/v1/search)
	Search(ctx echo.Context, params SearchParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetCart converts echo context to params.
func (w *ServerInterfaceWrapper) GetCart(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetCart(ctx)
	return err
}

// RemoveCart converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveCart(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RemoveCart(ctx, id)
	return err
}

// AddCart converts echo context to params.
func (w *ServerInterfaceWrapper) AddCart(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AddCart(ctx, id)
	return err
}

// GetFavorite converts echo context to params.
func (w *ServerInterfaceWrapper) GetFavorite(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetFavorite(ctx)
	return err
}

// RemoveFavorite converts echo context to params.
func (w *ServerInterfaceWrapper) RemoveFavorite(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RemoveFavorite(ctx, id)
	return err
}

// AddFavorite converts echo context to params.
func (w *ServerInterfaceWrapper) AddFavorite(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AddFavorite(ctx, id)
	return err
}

// GetMiniPost converts echo context to params.
func (w *ServerInterfaceWrapper) GetMiniPost(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMiniPostParams
	// ------------- Required query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, true, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Required query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, true, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameter("form", true, false, "sort", ctx.QueryParams(), &params.Sort)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sort: %s", err))
	}

	// ------------- Optional query parameter "user" -------------

	err = runtime.BindQueryParameter("form", true, false, "user", ctx.QueryParams(), &params.User)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user: %s", err))
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", ctx.QueryParams(), &params.Tag)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetMiniPost(ctx, params)
	return err
}

// CreatePost converts echo context to params.
func (w *ServerInterfaceWrapper) CreatePost(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreatePost(ctx)
	return err
}

// DeletePost converts echo context to params.
func (w *ServerInterfaceWrapper) DeletePost(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeletePost(ctx, id)
	return err
}

// FindPostByID converts echo context to params.
func (w *ServerInterfaceWrapper) FindPostByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.FindPostByID(ctx, id)
	return err
}

// UpdatePost converts echo context to params.
func (w *ServerInterfaceWrapper) UpdatePost(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdatePost(ctx, id)
	return err
}

// Search converts echo context to params.
func (w *ServerInterfaceWrapper) Search(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchParams
	// ------------- Required query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, true, "query", ctx.QueryParams(), &params.Query)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter query: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Search(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/v1/cart", wrapper.GetCart)
	router.DELETE(baseURL+"/api/v1/cart/:id", wrapper.RemoveCart)
	router.POST(baseURL+"/api/v1/cart/:id", wrapper.AddCart)
	router.GET(baseURL+"/api/v1/favorite", wrapper.GetFavorite)
	router.DELETE(baseURL+"/api/v1/favorite/:id", wrapper.RemoveFavorite)
	router.POST(baseURL+"/api/v1/favorite/:id", wrapper.AddFavorite)
	router.GET(baseURL+"/api/v1/post", wrapper.GetMiniPost)
	router.POST(baseURL+"/api/v1/post", wrapper.CreatePost)
	router.DELETE(baseURL+"/api/v1/post/:id", wrapper.DeletePost)
	router.GET(baseURL+"/api/v1/post/:id", wrapper.FindPostByID)
	router.PUT(baseURL+"/api/v1/post/:id", wrapper.UpdatePost)
	router.POST(baseURL+"/api/v1/search", wrapper.Search)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaX28TRxD/KqdtH0+xITz5LZCmTaWKqIT2geZh8a2Trc53x946bRRZ8h9VhQYVFSFR",
	"VQUElfp8mJiYJL58hdlvVO3une2z1/EFQpWQPBHv+Wbnz2/mNzNmG5X9auB7xOMhKm2jsLxBqlj9eYMR",
	"zMmKH3L5CbvuzQoq3dlGAfMDwjgl+luYk3Wfbcm/HRKWGQ049T1UQvAXRKIFXXgDsWhATzyaQzbiWwFB",
	"JRRyRr11VLfR4uhLEzJeQgy70BUNeAsR9KEHXQtieC1+E4+gAwfQlYdTRK9gvrFcxetaU8pJNTRc8Sfs",
	"KYkNiOCtlgddo7zkADOGt5R8RsvEIPFfJSXKr+gq5a5J0DOIYA862nLxKK/Auo0YuVejjDiodCeRnvV0",
	"qrw9DGDGX2v1tbqNvnAovwTA/wCAWxzzmkm3pxDBvmiIHdGC2IID6BmEZrS96/suwd7HgJXGBGM++2p1",
	"dUUKzkKh7DuG69QLlnpmo4rPqpijEqIen786vIN6nKwTJrWukjDE61MFpY9noT65MP26VH2p5rqXcL6E",
	"c6rm7ZCwZWdS4rJjwRHEcCAeKl92ksAfTJHzHSU/hUbAxNJE8St0RVO0oCNtPhINiEUTDiEWLfk3dOYM",
	"eTCG5kRVO38xT2KQameo7t9Qj85Kh48OOT/kxhAsniAtzigNHwOwxbMPsCQyI/hJMDaGo7qNQlKuMcq3",
	"bsnmUSPlLsGMsIUa3xh+Wkpr/9ffryJbt5oqxdXToYobnAeSbWxEvYo/afbNgHgLAbXm54oW7EqnWaKp",
	"amoHeqIJkRX4IZdnEbwTLYishSC47dF7yg06xig5sn6oFYvz5ZCwTVomljRanRBrYWUZ2WiTsFDfemWu",
	"OFeUwfAD4uGAohKaV0c2CjDfUFYXcEALm1cKZcxUVq0T9Y9MKCyVl1hAXxJ+Qz6X/g8D3wu1x64Wi5pD",
	"PU48nZNB4NKyerHwY6jpRPfnmVz0PZKk7ueMVFAJfVYY9vSFpKEvDJJdpX42DaWrx5D1fBLhKWTbEm7Q",
	"h3hOeuNq8ZoZmKIBe9DTCXgk2gqfkXrFIRVcc/mJrD3OtGFHYrLkhUqBnswzcR8OVD0Q96EHr2FfKTQC",
	"YOXFUejeWauv2SisVatYtgQIHiuc9UVbtMRDYyGw5F0W7A89IHb0LaPoKGxTp64d5xJOJlHyLan6myQB",
	"SoAZrhJOWKg0nGAryaaqiDSkRTJvUEmhEtnIwyrJqINGE56zGrFH/DveS62Z0TkLJdC1RBt2IUoOjkfJ",
	"K9kNQCwbqowJFvShK1oWdDJ+lJRyzuHzT+KbnobPJFJG/KCMDRJ+zoJjwXHOITJgV+YLRIPDFB3nOaJP",
	"BjYlMc1iVrSzuV/Bmz6jOuGnscNS+p0PZIh8dHD6xf+xAnbSDqoow+GQA+JPjQPGbe2aI56z4o8E/wJU",
	"fTOB9qXApmiLB2lfK9qSED7J8p+Bj9gRv+SmgHMKlQtDAzMKQxrXaTQwKNEzwmueAlViQRf2deiTsVBV",
	"4QfS6wpp0LFEA7qwJ9pyFhUt6ImGaIvf1XfeWdARO/Basdm+HugVcO7ViFoxJMjxK5WQ8DzoGRk+81nR",
	"gVhO3mqifQARdOFQKz5m3hTNXFqlH6zYSzm4iJakr2keCNNdy4TgwfrKIPhvWdMghl05qsaiod2vEnUf",
	"elPv8lXjNz0z7dnbhrF9g+maWqhG8hNcA6+gC2+myeN4Hb1HPTk347Aa8qZ2RKI5Zc87ua4ZyjqD9XC0",
	"CUozM5KT2iFEoima0JPYUq7RzR50juGwkV8YdY6SkF/3na1Ts3jkgnp24SXrQH0CclfGbubkZ14IXEzH",
	"7nzfXWUeZKlmSjThCLrivuQNVR1gT7UOnwJVvkyt0UTZVxUpNuaHiTJn9tGL6jwPcx4TuI/RIJkqwwvj",
	"FvjhoJ8Wf0BfRfya8fUng+bisps2o8c291dL1HMkRK5vLS+eMZic3pA/+L0zb+ExDvkXB3n517yJryzq",
	"aHqrGSB2O3DwWalDp0+tg/8akotYr+VeI2SYTw1VmiAOLiQic9fC5wNHHVsNR7g0JJiV1a9z5ubsln4+",
	"a/h8ClHawk7p/NOPZ6Mmnmzxedy6wozqZ3qE1RiUcIM+RPAOdjV+ddlIejm1GRVtC/aGTlQL4zNeHWXT",
	"0hNN2J/T0kLCNlN41Jib/IQblgqF7Q0/5BIHdQk7ZKNNzCi+6+q4pg+1GxODkeuXsbuRhGit/l8AAAD/",
	"/+djSZaiKAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
