// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package delivery

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserCheck struct {
	Login                string   `protobuf:"bytes,1,opt,name=Login,proto3" json:"Login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCheck) Reset()         { *m = UserCheck{} }
func (m *UserCheck) String() string { return proto.CompactTextString(m) }
func (*UserCheck) ProtoMessage()    {}
func (*UserCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCheck.Unmarshal(m, b)
}
func (m *UserCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCheck.Marshal(b, m, deterministic)
}
func (m *UserCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCheck.Merge(m, src)
}
func (m *UserCheck) XXX_Size() int {
	return xxx_messageInfo_UserCheck.Size(m)
}
func (m *UserCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCheck.DiscardUnknown(m)
}

var xxx_messageInfo_UserCheck proto.InternalMessageInfo

func (m *UserCheck) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *UserCheck) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type BoolValue struct {
	Value                bool     `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolValue) Reset()         { *m = BoolValue{} }
func (m *BoolValue) String() string { return proto.CompactTextString(m) }
func (*BoolValue) ProtoMessage()    {}
func (*BoolValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *BoolValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolValue.Unmarshal(m, b)
}
func (m *BoolValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolValue.Marshal(b, m, deterministic)
}
func (m *BoolValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolValue.Merge(m, src)
}
func (m *BoolValue) XXX_Size() int {
	return xxx_messageInfo_BoolValue.Size(m)
}
func (m *BoolValue) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolValue.DiscardUnknown(m)
}

var xxx_messageInfo_BoolValue proto.InternalMessageInfo

func (m *BoolValue) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func init() {
	proto.RegisterType((*UserCheck)(nil), "delivery.UserCheck")
	proto.RegisterType((*BoolValue)(nil), "delivery.BoolValue")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x49, 0xcd, 0xc9, 0x2c, 0x4b, 0x2d, 0xaa,
	0x54, 0xb2, 0xe5, 0xe2, 0x0c, 0x2d, 0x4e, 0x2d, 0x72, 0xce, 0x48, 0x4d, 0xce, 0x16, 0x12, 0xe1,
	0x62, 0xf5, 0xc9, 0x4f, 0xcf, 0xcc, 0x93, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84,
	0xa4, 0xb8, 0x38, 0x02, 0x12, 0x8b, 0x8b, 0xcb, 0xf3, 0x8b, 0x52, 0x24, 0x98, 0xc0, 0x12, 0x70,
	0xbe, 0x92, 0x22, 0x17, 0xa7, 0x53, 0x7e, 0x7e, 0x4e, 0x58, 0x62, 0x4e, 0x69, 0x2a, 0x48, 0x3b,
	0x98, 0x01, 0xd6, 0xce, 0x11, 0x04, 0xe1, 0x18, 0x39, 0x71, 0xb1, 0x80, 0x6c, 0x10, 0xb2, 0xe2,
	0xe2, 0x01, 0xdb, 0xe2, 0x98, 0x9c, 0x9c, 0x5f, 0x9a, 0x57, 0x22, 0x24, 0xac, 0x07, 0x73, 0x84,
	0x1e, 0xdc, 0x05, 0x52, 0x48, 0x82, 0x70, 0x73, 0x95, 0x18, 0x9c, 0x78, 0xa3, 0xb8, 0xf5, 0xf4,
	0xad, 0x61, 0x52, 0x49, 0x6c, 0x60, 0x5f, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x52,
	0xe0, 0x19, 0xd3, 0x00, 0x00, 0x00,
}
