version: "3.9"
services:

  user-service:
    image: user
    container_name: "user"
    command: ./app
    ports:
      - 10000:8000
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "user"
      POSTGRES_USER: "appuniq"
      POSTGRES_PASSWORD: "uniq123"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"