version: "3.9"
services:

  user-service:
    container_name: "user"
    build: ./
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: "postgres_user"
    image: postgres
    environment:
      POSTGRES_DB: "user"
      POSTGRES_USER: "appuniq"
      POSTGRES_PASSWORD: "uniq123"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U appuniq -d user"]
        interval: 10s
        timeout: 5s
        retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"