version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "user"
      POSTGRES_USER: "appimage"
      POSTGRES_PASSWORD: "uniq123"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5433:5433"