openapi: "3.0.0"
info:
  version: 1.0.0
  title: AppUniq <service Post> API
  description: OpenApi 3.0 для сервиса post сайта AppUniq.
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
paths:
  /api/sort/new/{page}:
      get:
        summary: Основнвая страница
        operationId: getAllPost
        parameters:
          - name: page
            in: path
            description: Номер странитцы в отсортированной бд, от нового к старому.
            required: true
            schema:
              type: string
        responses:
          '200':
            description: Объявления получены.
            content:
              application/json:
                 schema:
                  type: array
                  items:
                    oneOf:
                      - $ref: '#/components/schemas/MiniPost'
          '204':
            description: Были просмотренны все объявления.
  
          default:
            description: Произошла ошибка.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorHTTP'
  /api/post:
    get:
      summary: Вернуть посты авторизированного пользователя.
      operationId: Post
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Объявление получено.
          content:
            application/json:
               schema:
                 type: array
                 items:
                    oneOf:
                      - $ref: '#/components/schemas/MiniPost'
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
  
    post:
      summary: Создать новое объявление.
      operationId: createPost
      security:
      - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePost'
      responses:
        '201':
          description: Объявление успешно создано.
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
  /api/post/{id}:
    get:
      summary: Вернуть объявление по id.
      operationId: findPostByID
      parameters:
        - name: id
          in: path
          description: ID объявления.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Объявление получено.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
    put:
      summary: Обновить объявление.
      operationId: updatePost
      security:
      - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID объявления.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          description: Объявление успешно обновлено.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
    delete:
      summary: Удалить объявление.
      operationId: deletePost
      security:
      - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID объявления.
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Пользователь удалён.
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
  /api/close/{id}:
    put:
      summary: Закрыть объявление.
      operationId: closePost
      security:
      - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID объявления.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Объявление успешно обновлено.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
  /api/post/user/{id}:
    get:
      summary: Вернуть объявления по id пользователя.
      operationId: findPostByUserID
      parameters:
        - name: id
          in: path
          description: ID пользоввателя.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Объявления получено.
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: '#/components/schemas/Post'
        '204':
            description: Были просмотренны все объявления.
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
                
  /api/favorite/{id}:
    post:
      summary: Добавить объявление в избранное по id поста.
      operationId: addFavoritePost
      security:
      - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID поста.
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Объявление добавлено.
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
        
    delete:
      summary: Удалить объявление по id поста.
      operationId: removeFavoritePost
      security:
      - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID поста.
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Объявление удалено.
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
                
  /api/favorite/{page}:
    get:
      summary: Вернуть избранное пользователя.
      operationId: addFavoritePodst
      security:
      - bearerAuth: []
      parameters:
        - name: page
          in: path
          description: страница.
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Объявление добавлено.
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
                

components:
  schemas:
    MiniPost:
      allOf:
        - required:
            - UserId
            - Title
            - Name
            - PostId
            - Views
            - Price
            - ImageMassive
          properties:
            UserId:
              type: string
              description: ID пользователя.
            Name:
              type: string
              description: Имя пользователя.
            PostId:
              type: string
              description: ID объявления.
            Title:
              type: string
              description: Названия объявления.
            Views:
              type: integer
              description: Количество просмотров.
            Price:
              type: string
              description: Цена объявления.
            ImageMassive:
              $ref: '#/components/schemas/ImageMassive'  
  
  
    CreatePost:
      allOf:
        - required:
            - UserId
            - Title
            - Description
            - Price
            - Close
            - ImageMassive
          properties:
            Title:
              type: string
              description: Названия объявления.
            Description:
              type: string
              description: Содержание объявления.
            Price:
              type: string
              description: Цена объявления.
            ImageMassive:
              $ref: '#/components/schemas/ImageMassive'
              
    Post:
      allOf:
        - required:
            - UserId
            - Title
            - Description
            - Price
            - Close
            - ImageMassive
          properties:
            UserId:
              type: string
              description: Id пользователя.
            Title:
              type: string
              description: Названия объявления.
            Description:
              type: string
              description: Содержание объявления.
            Views:
              type: integer
              description: Количество просмотров.
            FavoriteAdd:
              type: integer
              description: Количество добавлений в избранное.
            Price:
              type: string
              description: Цена объявления.
            Close:
              type: boolean
              description: Закрыто ли объявление.
            ImageMassive:
              $ref: '#/components/schemas/ImageMassive'
              
              
    ImageMassive:
      type: array
      items:
        oneOf:
          - required:
              - Image
            properties:
              Image: 
                type: string
                description: Изображение объявления.
                
            

    ErrorHTTP:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
          
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
