openapi: "3.0.0"
info:
  version: 1.0.0
  title: AppUniq <service Post> API
  description: OpenApi 3.0 для сервиса post сайта AppUniq.
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
paths:
  /sort/new/{post}:
      get:
        summary: Основнвая страница
        operationId: getAllPost
        parameters:
          - name: post
            in: path
            description: Номер поста в отсортированной бд, от нового к старому.
            required: true
            schema:
              type: string
        responses:
          '200':
            description: Объявления получены.
            content:
              application/json:
                 schema:
                   $ref: '#/components/schemas/Post'
          '204':
            description: Были просмотренны все объявления.
  
          default:
            description: Произошла ошибка.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorHTTP'
  /post:
    get:
      summary: Вернуть посты авторизированного пользователя.
      operationId: getPost
      responses:
        '200':
          description: Объявление получено.
          content:
            application/json:
               schema:
                 type: array
                 items:
                    oneOf:
                      - $ref: '#/components/schemas/Post'
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
  
    post:
      summary: Создать новое объявление.
      operationId: createPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          description: Объявление успешно создано.
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
  /post/{id}:
    get:
      summary: Вернуть объявление по id.
      operationId: findPostByID
      parameters:
        - name: id
          in: path
          description: ID объявления.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Объявление получено.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
    put:
      summary: Обновить объявление.
      operationId: updatePost
      parameters:
        - name: id
          in: path
          description: ID объявления.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          description: Объявление успешно обновлено.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
    delete:
      summary: Удалить объявление.
      operationId: deletePost
      parameters:
        - name: id
          in: path
          description: ID объявления.
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Пользователь удалён.
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
  /close/{id}:
    put:
      summary: Закрыть объявление.
      operationId: closePost
      parameters:
        - name: id
          in: path
          description: ID объявления.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Объявление успешно обновлено.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
  /cart:
    get:
      summary: Вернуть корзину товаров.
      operationId: getShopingCart
      responses:
        '200':
          description: Корзина получена.
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: '#/components/schemas/PostId'
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
    post:
      summary: Добавить товар в корзину.
      operationId: addCart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostId'
      responses:
        '201':
          description: Товар успешно добвавлен.
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
  /cart/{id}:
    delete:
      summary: Убрать товар из корзины.
      operationId: removeCart
      parameters:
        - name: id
          in: path
          description: ID объявления.
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Объявление удалено.
        default:
          description: Произошла ошибка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorHTTP'
components:
  schemas:
    Post:
      allOf:
        - required:
            - Title
            - Description
            - Price
            - Close
            - ImageMassive
          properties:
            Title:
              type: string
              description: Названия объявления.
            Description:
              type: string
              description: Содержание объявления.
            Price:
              type: string
              description: Цена объявления.
            Close:
              type: boolean
              description: Закрыто ли объявление.
            ImageMassive:
              $ref: '#/components/schemas/ImageMassive'
              
    ImageMassive:
      type: array
      items:
        oneOf:
          - required:
              - Image
            properties:
              Image: 
                type: string
                description: Изображение объявления.
                
    PostId:
      allOf:
        - required:
            - Id
          properties:
            Id:
              type: string
              description: Идентификатор объявления.
            

    ErrorHTTP:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message